stolostron/search-operator

- go.mod
- go.sum
For issue open-cluster-management/backlog#9809
> [release 2.1]update golang.org/x/text version

- config/crd/bases/search.open-cluster-management.io_searchcustomizations.yaml
- config/crd/bases/search.open-cluster-management.io_searchoperators.yaml
Reflecting the change in https://github.com/open-cluster-management/hub-crds/pull/20
For https://github.com/open-cluster-management/backlog/issues/10696
> update crd apiVersion to apiextensions.k8s.io/v1

- README.md
- build/Dockerfile
- go.sum
For https://github.com/open-cluster-management/backlog/issues/11044
> dummy update for base image rebuild

- controllers/searchoperator_controller.go
- controllers/searchoperator_controller_test.go
Restart collector if Redisgraph has been disabled for a while.
For https://github.com/open-cluster-management/backlog/issues/10931
> Restart collector pod when enabling redisgraph

- Dockerfile
Disabled deployment of RedisGraph by default upstream.
Issue: open-cluster-management/backlog#10931
> Turn off DEPLOY_REDISGRAPH flag

- Dockerfile
Reverts open-cluster-management/search-operator#58
> Revert "Turn off DEPLOY_REDISGRAPH flag"

- Dockerfile
Issue: https://bugzilla.redhat.com/show_bug.cgi?id=1967953
> Set user 1001 (non root) in Docker image

- cicd-scripts/run-e2e-tests.sh
- controllers/searchoperator_controller.go
Update search operator status even if reconcile function errors out.
Related to open-cluster-management/backlog/issues/13483
> update search operator status in case of error

- controllers/searchoperator_controller.go
Porting change for this [issue](https://github.com/open-cluster-management/backlog/issues/13661) into release 2.3
> restart statefulset in case of metadata changes

- controllers/searchoperator_controller.go
For https://github.com/open-cluster-management/backlog/issues/13661
> [release 2.2] Restart statefulset in case of metadata changes

- controllers/searchoperator_controller.go
> [release 2.2] Remove extra comments

- .travis.yml
Remove sonar and fast forward, related issue open-cluster-management/backlog#10511
> Remove Sonar and Fast Foward

- Dockerfile
Issue: https://github.com/open-cluster-management/backlog/issues/14455
> [2.3] Update to ubi-minimal:8.4

- README.md
Rebuilding imagescan for open-cluster-management/search-operator repo.
> Imagescan Rebuild: 2021-09-12

- README.md
Signed-off-by: Sherin Varughese <shvarugh@redhat.com>
The previous [PR](https://github.com/stolostron/search-operator/pull/101) failed on post-submit publish https://github.com/stolostron/search-operator/commit/3eb5928d6ed02ef685ccfc4edecb16821c78a5d4. Retrigger prow with this PR.
> Retrigger prow

- README.md
https://github.com/stolostron/backlog/issues/21304
Signed-off-by: Sherin Varughese <shvarugh@redhat.com>
> Rebuild 2.5

- controllers/searchoperator_controller.go
Signed-off-by: xavier dharmaiyan <xavier@redhat.com>
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2065318
Github Issue: https://github.com/stolostron/backlog/issues/20824
>  [release-24] update liveness port to 6379

- README.md
Signed-off-by: Anxhela <acoba@redhat.com>
**Related Issue:**  stolostron/backlog#22533
No-op pr to trigger image scan
> No-op pr to trigger image scan

- README.md
Signed-off-by: Sherin Varughese <shvarugh@redhat.com>
**Related Issue:**  [stolostron/backlog#23712](https://github.com/stolostron/backlog/issues/23712)
> trigger rebuild

- OWNERS
Signed-off-by: dislbenn <dbennett@redhat.com>
**Related Issue:**  stolostron/backlog#24364
> [release-2.4] Removed duplicate users from reviewers

- Dockerfile
- go.mod
Signed-off-by: Xavier Dharmaiyan <xavier@redhat.com>
**Related Issue:**  stolostron/backlog#24212
>  [release 2.5] updated to go 1.18

- Dockerfile
- go.mod
Signed-off-by: Xavier Dharmaiyan <xavier@redhat.com>
**Related Issue:**  stolostron/backlog#24212
> [release 2.4] updated to go 1.18

- addon/addon.go
- addon/addon_test.go
- addon/manifests/chart/templates/deployment.yaml
- addon/manifests/chart/values.yaml
Signed-off-by: Xavier Dharmaiyan <xavier@redhat.com>
**Related Issue:**  stolostron/backlog#18606
>  customize klusterlet search

- Dockerfile
**Changes:** Update CGO_ENABLED to 1.
> [release-2.6] Update CGO_ENABLED to 1

- Dockerfile
**Changes:** Update CGO_ENABLED to 1.
> [main] Update CGO_ENABLED to 1
